workspace//home/runner/work/community-plugins/community-plugins/workspaces/3scale:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/3scale"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/acr:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/acr"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/acs:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/acs"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/adr:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/adr"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/agent-forge:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/agent-forge"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/airbrake:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/airbrake"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/allure:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/allure"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/amplication:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/amplication"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/analytics:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/analytics"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/announcements:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/announcements"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/apache-airflow:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/apache-airflow"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/apollo-explorer:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/apollo-explorer"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/azure-devops:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/azure-devops"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/azure-resources:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/azure-resources"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/azure-sites:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/azure-sites"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/azure-storage-explorer:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/azure-storage-explorer"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/badges:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/badges"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/bazaar:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/bazaar"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/bitbucket-pull-requests:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/bitbucket-pull-requests"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/bitrise:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/bitrise"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/blackduck:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/blackduck"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/bookmarks:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/bookmarks"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/cicd-statistics:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/cicd-statistics"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/cloudbuild:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/cloudbuild"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/code-climate:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/code-climate"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/code-coverage:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/code-coverage"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/codescene:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/codescene"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/confluence:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/confluence"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/copilot:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/copilot"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/cost-insights:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/cost-insights"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/dynatrace:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/dynatrace"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/entity-feedback:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/entity-feedback"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/entity-validation:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/entity-validation"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/explore:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/explore"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/feedback:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/feedback"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/firehydrant:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/firehydrant"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/flux:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/flux"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/fossa:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/fossa"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/gcalendar:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/gcalendar"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/gcp-projects:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/gcp-projects"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/git-release-manager:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/git-release-manager"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/github-actions:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/github-actions"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/github-deployments:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/github-deployments"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/github-discussions:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/github-discussions"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/github-issues:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/github-issues"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/github-pull-requests-board:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/github-pull-requests-board"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/gitops-profiles:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/gitops-profiles"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/gocd:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/gocd"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/grafana:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/grafana"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/graphiql:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/graphiql"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/graphql-voyager:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/graphql-voyager"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/ilert:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/ilert"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/jaeger:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/jaeger"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/jenkins:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/jenkins"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/jfrog-artifactory:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/jfrog-artifactory"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/kafka:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/kafka"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/keycloak:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/keycloak"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/kiali:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/kiali"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/lighthouse:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/lighthouse"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/linguist:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/linguist"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/linkerd:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/linkerd"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/manage:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/manage"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/mcp-chat:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/mcp-chat"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/mend:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/mend"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/microsoft-calendar:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/microsoft-calendar"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/mta:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/mta"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/multi-source-security-viewer:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/multi-source-security-viewer"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/newrelic:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/newrelic"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/nexus-repository-manager:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/nexus-repository-manager"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/nomad:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/nomad"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/npm:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/npm"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/ocm:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/ocm"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/octopus-deploy:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/octopus-deploy"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/opencost:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/opencost"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/periskop:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/periskop"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/pingidentity:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/pingidentity"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/playlist:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/playlist"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/puppetdb:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/puppetdb"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/quay:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/quay"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/rbac:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/rbac"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/redhat-argocd:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/redhat-argocd"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/report-portal:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/report-portal"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/rollbar:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/rollbar"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-backend-module-annotator:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-backend-module-annotator"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-backend-module-kubernetes:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-backend-module-kubernetes"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-backend-module-regex:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-backend-module-regex"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-backend-module-servicenow:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-backend-module-servicenow"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-backend-module-sonarqube:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-backend-module-sonarqube"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-relation-processor:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/scaffolder-relation-processor"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/sentry:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/sentry"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/servicenow:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/servicenow"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/shortcuts:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/shortcuts"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/sonarqube:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/sonarqube"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/splunk:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/splunk"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/stack-overflow:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/stack-overflow"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/stackstorm:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/stackstorm"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/tech-insights:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/tech-insights"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/tech-radar:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/tech-radar"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/tekton:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/tekton"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/todo:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/todo"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/topology:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/topology"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/vault:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/vault"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/wheel-of-names:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/wheel-of-names"

workspace//home/runner/work/community-plugins/community-plugins/workspaces/xcmetrics:
  - "Workspace\\s*/home/runner/work/community-plugins/community-plugins/workspaces/xcmetrics"

needs-triaging:
  - "Workspace\\s*Select a workspace..."